name: Generate xml sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate sitemap
        run: |
          # Your sitemap generation script here
          echo "Sitemap generated"

      - name: Commit sitemap
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add sitemap.xml
          git commit -m "Automated sitemap update"
          git push origin main
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
