name: Generate Sitemap

on:
  push:
    branches:
      - main  # Ganti dengan nama branch utama Anda jika berbeda

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Penting untuk mendapatkan riwayat commit lengkap

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: "https://ramado1244.github.io"  # Ganti dengan URL GitHub Pages Anda
          base-url-path: "https://ramado1244.github.io/ramado21/"
          include-extensions: "html"
          path-to-root: .

      - name: Deploy to GitHub Pages
        run: |
          # Tambahkan perintah untuk menyalin sitemap.xml ke direktori yang akan dideploy
          # Misalnya, jika Anda menggunakan direktori 'docs/' sebagai sumber GitHub Pages:
          cp sitemap.xml ramado21/
          # Tambahkan perintah lain yang diperlukan untuk proses deploy
